import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import QueryProvider from "@/app/queryProvider";
import WithCurrentUser from "@/loaders/currentUser/withCurrentUser";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <QueryProvider>
      {children}
    </QueryProvider>
    </body>
    </html>
  )
}
